version: "3"
services:
  postgres:
    container_name: postgres-symlink
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/data/postgres
      - postgresdbdata:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
