"""initial_migration

Revision ID: 4d4c84a036f9
Revises: 
Create Date: 2024-09-26 16:29:21.547585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4c84a036f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('token_size', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('system_message', sa.String(), nullable=True),
    sa.Column('frequency_penalty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sensitivity_score', sa.JSON(), nullable=True),
    sa.Column('sesitive_tokens', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_name'], ['configurations.model_name'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('sent_by', sa.String(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('masked_content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    op.drop_table('sessions')
    op.drop_table('configurations')
    # ### end Alembic commands ###
